############################################
# Application
############################################
spring.application.name=YAHO
server.port=8090


############################################
# MySQL Database (Example)
############################################
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/YOUR_DB_NAME
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD


############################################
# Oracle Database (Example)
############################################
spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.oracle.jdbc-url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.oracle.username=YOUR_ORACLE_USERNAME
spring.datasource.oracle.password=YOUR_ORACLE_PASSWORD


############################################
# File Upload Path
############################################
profile.upload.path=/your/upload/path


############################################
# File Upload Limit
############################################
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


############################################
# Email Configuration (Example)
############################################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL_ADDRESS
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


############################################
# Logging
############################################
#logging.level.com.yaho=INFO
#logging.file.name=logs/default.log